markdown: kramdown
timezone: Europe/Rome
title: FutureGateway Framework
author: Riccardo Bruno
authweb: "https://ricsxn.github.io"
email: "riccardo.bruno@ct.infn.it"
description: >-
  FutureGateway Framework is a complete framework to build Science Gateways.
  This web site keeps updated information about this software initiative.
baseurl: ""
url: "https://futuregatewayframework.github.io"
repourl: "https://github.com/FutureGatewayFramework"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
logo: images/fglogo_32.png
show_downloads: [false]
google_analytics: UA-147537176-1
future: true
#twitter_username: ricsxn
linkedin_username: riccardo-bruno-b333931
github_username: ricsxn








