theme: jekyll-theme-minimal
title: [FutureGateway Framework]
description: [A complete framework to buil fastly and securely Science Gateways]
logo: [images/fglogo.png]
show_downloads: [false]
google_analytics: UA-147537176-1

